### PR TITLE
add createFederationToken endpoint

### PR DESCRIPTION
**Pull request by hanshasselberg**

### CODE REVIEW

**Comment by hanshasselberg** [comment]
This needs its own tag once merged. https://hashicorp.atlassian.net/wiki/spaces/CLOUD/pages/695763358/API+Versioning+Consul+AMA: 

> Create a version tag of your cloud-consul-ama-api-spec changes. Each API version should have its own tag.

**Review by daneharrigan — APPROVED** [review]
This looks good, but I think one line is out of date with consul-ama. The date in this file is 2020-09-08, but the date in consul-ama is [2020-09-09](https://github.com/hashicorp/cloud-consul-ama/pull/398/files#diff-c66d3259beb571aafe14e36226bb4a47R16). Should these values be the same?

Other than that, this looks good to me.

**Comment by hanshasselberg** [comment]
@daneharrigan good catch! Fixed that. Running `make proto/compile` in `cloud-consul-ama` was not enough, I had to run `make proto` to update this version.

**Comment by hanshasselberg** [comment]
Tag created: https://github.com/hashicorp/cloud-consul-ama-api-spec/tree/2020-09-09.

**Pull request merged**
